### ISSUE TITLE
Include Executable Files in Releases

### ISSUE THREAD

**Issue by shahriaarrr** [neox1de/tasky-rs#1]
I was wondering if you could add executable files (or builds) for different distributions and OS like Windows with each release. It would make life so much easier for people who just want to download and use the app without having to build it themselves.
keep up the awesome work! 🙌
Let me know if you need help testing or anything✌️❤️💣

**Comment by neox1de** [comment]
Thanks @shahriaarrr - I'll add pre-built executables for different Operating Systems as soon as possible 👍

**Comment by neox1de** [comment]
@shahriaarrr i've solved this in commit 0b329e0

i'll close this issue now.
